#!/usr/bin/env Rscript
# =========================================================
# plot_global_accessibility.R
# ---------------------------------------------------------
# Produces publication-style plots from the
# global_accessibility_summary.csv generated by
# global_accessibility_check.R.
#
# Usage:
#   Rscript plot_global_accessibility.R \
#     <global_accessibility_summary.csv> \
#     <out_dir>
# =========================================================

args     <- commandArgs(trailingOnly = TRUE)
csv_file <- args[1]
out_dir  <- args[2]

dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

suppressPackageStartupMessages({
  library(ggplot2)
  library(tidyr)
  library(dplyr)
})

df <- read.csv(csv_file, stringsAsFactors = FALSE)

# Condition order
cond_order <- c("DMSO", "PY60", "PRBJN", "PRBJNsorted", "DUX4sorted")
df$condition <- factor(df$condition, levels = cond_order)

cond_colors <- c(
  DMSO        = "#888780",
  PY60        = "#1D9E75",
  PRBJN       = "#BA7517",
  PRBJNsorted = "#D4537E",
  DUX4sorted  = "#7F77DD"
)

# --- Plot 1: hkTSS fold change (the most meaningful) ------------------------
p1 <- ggplot(df, aes(x = condition, y = hkTSS_fc, color = condition)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50", linewidth = 0.6) +
  geom_jitter(width = 0.1, size = 4, alpha = 0.9) +
  stat_summary(fun = mean, geom = "crossbar",
               width = 0.4, linewidth = 0.6, fatten = 2,
               color = "grey30") +
  scale_color_manual(values = cond_colors) +
  scale_y_continuous(limits = c(0.7, 1.7),
                     breaks = seq(0.7, 1.7, 0.1),
                     labels = function(x) paste0(x, "x")) +
  theme_bw(base_size = 13) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1)) +
  labs(x = NULL,
       y = "Global accessibility fold change vs DMSO",
       title = "Global chromatin accessibility - hkTSS normalization",
       subtitle = "Each dot = one replicate | crossbar = mean | dashed = DMSO reference")

ggsave(file.path(out_dir, "global_accessibility_hkTSS_fc.pdf"),
       p1, width = 7, height = 6)
ggsave(file.path(out_dir, "global_accessibility_hkTSS_fc.png"),
       p1, width = 7, height = 6, dpi = 300)

# --- Plot 2: all normalization methods side by side -------------------------
fc_long <- df %>%
  select(sample, condition, raw_fc, stablePeak_fc, hkTSS_fc) %>%
  pivot_longer(cols = c(raw_fc, stablePeak_fc, hkTSS_fc),
               names_to = "method", values_to = "fold_change") %>%
  mutate(method = recode(method,
    raw_fc         = "Raw counts",
    stablePeak_fc  = "stablePeak",
    hkTSS_fc       = "hkTSS"
  ),
  method = factor(method, levels = c("Raw counts", "stablePeak", "hkTSS")))

p2 <- ggplot(fc_long, aes(x = condition, y = fold_change, color = condition)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "grey50", linewidth = 0.5) +
  geom_jitter(width = 0.1, size = 3, alpha = 0.9) +
  stat_summary(fun = mean, geom = "crossbar",
               width = 0.4, linewidth = 0.5, fatten = 2,
               color = "grey30") +
  facet_wrap(~method, scales = "free_y", nrow = 1) +
  scale_color_manual(values = cond_colors) +
  scale_y_continuous(labels = function(x) paste0(x, "x")) +
  theme_bw(base_size = 11) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 40, hjust = 1, size = 9),
        strip.background = element_rect(fill = "grey95"),
        strip.text = element_text(face = "bold")) +
  labs(x = NULL,
       y = "Fold change vs DMSO",
       title = "Global chromatin accessibility across normalization methods",
       subtitle = "Each dot = one replicate | crossbar = mean")

ggsave(file.path(out_dir, "global_accessibility_all_methods.pdf"),
       p2, width = 12, height = 6)
ggsave(file.path(out_dir, "global_accessibility_all_methods.png"),
       p2, width = 12, height = 6, dpi = 300)

message("Done.")
message(sprintf("  %s/global_accessibility_hkTSS_fc.pdf", out_dir))
message(sprintf("  %s/global_accessibility_all_methods.pdf", out_dir))
